apiVersion: v1
kind: service
metadata:
  name:  myphpimage1june22:1-svc
  labels:
    app:  myphpimage1june22:1
    version: 2.6.1
spec:
  type: NodePort
  ports: 
  - port: 8080
    NodePort: 30001
    protocol: TCP
  selector:
     app:  myphpimage1june22:1
     version: 2.6.1